#!/bin/bash

set -e

cd "$(dirname "$0")/../builtinFonts"

font_id() {
  python3 -c 'import hashlib, sys; print(sum(int(hashlib.sha256(open(path, "rb").read()).hexdigest(), 16) for path in sys.argv[1:]) % (2 ** 32) - (2 ** 31))' "$@"
}

emit_id() {
  local name="$1"
  shift
  echo "#define ${name} ($(font_id "$@"))"
}

echo "// The contents of this file are generated by ./lib/EpdFont/scripts/build-font-ids.sh"
echo "#pragma once"
echo

emit_id NOTOSERIF_12_FONT_ID \
  ./notoserif_12_regular.h ./notoserif_12_bold.h ./notoserif_12_bolditalic.h ./notoserif_12_italic.h
emit_id NOTOSERIF_14_FONT_ID \
  ./notoserif_14_regular.h ./notoserif_14_bold.h ./notoserif_14_bolditalic.h ./notoserif_14_italic.h
emit_id NOTOSERIF_16_FONT_ID \
  ./notoserif_16_regular.h ./notoserif_16_bold.h ./notoserif_16_bolditalic.h ./notoserif_16_italic.h
emit_id NOTOSERIF_18_FONT_ID \
  ./notoserif_18_regular.h ./notoserif_18_bold.h ./notoserif_18_bolditalic.h ./notoserif_18_italic.h

emit_id NOTOSANS_12_FONT_ID \
  ./notosans_12_regular.h ./notosans_12_bold.h ./notosans_12_bolditalic.h ./notosans_12_italic.h
emit_id NOTOSANS_14_FONT_ID \
  ./notosans_14_regular.h ./notosans_14_bold.h ./notosans_14_bolditalic.h ./notosans_14_italic.h
emit_id NOTOSANS_16_FONT_ID \
  ./notosans_16_regular.h ./notosans_16_bold.h ./notosans_16_bolditalic.h ./notosans_16_italic.h
emit_id NOTOSANS_18_FONT_ID \
  ./notosans_18_regular.h ./notosans_18_bold.h ./notosans_18_bolditalic.h ./notosans_18_italic.h

# These legacy UI IDs are already used by the renderer and persisted caches.
# Keep them stable even though their generated headers have evolved since the
# original ID snapshot; only new font families use freshly derived IDs.
echo '#define UI_10_FONT_ID (22918846)'
echo '#define UI_12_FONT_ID (1635686837)'
echo '#define SMALL_FONT_ID (674098198)'
emit_id CJK_UI_10_FONT_ID ./notosanssc_gb2312_10_regular.h
emit_id CJK_READER_14_FONT_ID ./notosanssc_gb2312_14_regular.h

echo
echo '// Font ID 0 is reserved as the "not found" sentinel.'
echo '// Guard against any hash accidentally producing 0.'
for name in \
  NOTOSERIF_12_FONT_ID NOTOSERIF_14_FONT_ID NOTOSERIF_16_FONT_ID NOTOSERIF_18_FONT_ID \
  NOTOSANS_12_FONT_ID NOTOSANS_14_FONT_ID NOTOSANS_16_FONT_ID NOTOSANS_18_FONT_ID \
  UI_10_FONT_ID UI_12_FONT_ID SMALL_FONT_ID CJK_UI_10_FONT_ID CJK_READER_14_FONT_ID; do
  echo "static_assert(${name} != 0, \"Font ID collision with sentinel\");"
done
